### PR TITLE
Move Reference File Generator Scripts to astrogrism.HST

### PR DESCRIPTION
**Pull request by duytnguyendtn**
Reference file generators are missing during install. This PR is to try and reinclude them.

Originally, the scripts lived in the same configuration folder the reference files lived in. This folder was marked as a "data" directory: https://github.com/duytnguyendtn/astrogrism/blob/cc2262bfa20a3466b6a8f774fb9dbed4db56ea46/setup.cfg#L48-L49. @pllim suggested this might be the reason why I found the files were copied into the tar ball:
```
$ python .\setup.py sdist
running sdist
running egg_info
writing astrogrism.egg-info\PKG-INFO
...
copying astrogrism\config\HST\reference_file_generators\__init__.py -> astrogrism-1.0.2.dev120+gcc2262b.d20220316\astrogrism\config\HST\reference_file_generators
copying astrogrism\config\HST\reference_file_generators\common.py -> astrogrism-1.0.2.dev120+gcc2262b.d20220316\astrogrism\config\HST\reference_file_generators
copying astrogrism\config\HST\reference_file_generators\generate_distortion.py -> astrogrism-1.0.2.dev120+gcc2262b.d20220316\astrogrism\config\HST\reference_file_generators
copying astrogrism\config\HST\reference_file_generators\generate_specwcs.py -> astrogrism-1.0.2.dev120+gcc2262b.d20220316\astrogrism\config\HST\reference_file_generators
copying astrogrism\config\HST\reference_file_generators\generate_wavelengthrange.py -> astrogrism-1.0.2.dev120+gcc2262b.d20220316\astrogrism\config\HST\reference_file_generators
copying astrogrism\config\HST\reference_file_generators\wcs_ref_model.py -> astrogrism-1.0.2.dev120+gcc2262b.d20220316\astrogrism\config\HST\reference_file_generators
...
```
yet wasn't actually copied into `site-packages` when I installed that tar ball directly:
 
image

When I moved the files over (and tweaked a few of the imports, that seemed to fix the problem. And when I did a test and copied the working structure back into the `config` data folder, it broke again. So I'm confident with saying that was the issue. Thanks for saving me so much head-banging @pllim!!

@rosteen We'll probably want to get this before #21 and give you a chance to move your changes to the new location

### CODE REVIEW

**Comment by rosteen** [comment]
Looks fine to me...it still irrationally irks me to put stuff in "HST" folders because I hope for it to be more general, but...we only support HST right now 😆

**Review by rosteen — APPROVED** [review]

**Comment by duytnguyendtn** [comment]
> it still irrationally irks me to put stuff in "HST" folders
Definitely see your point here, and I was tempted to put this into a new "utils" folder. But then I realized this code itself is written specifically for HST (and the method itself is specifically `create_HST_reffiles` so I figured it was appropriate **for now**. I am absolutely with you when we finally genericize this enough to incorporate other telescopes, we should move this out of `astrogrism.HST` ASAP.

Thanks for the quick review/merge!

**Comment by rosteen** [comment]
> this code itself is written specifically for HST (and the method itself is specifically `create_HST_reffiles` so I figured it was appropriate **for now**. 

I did say it was irrational 😁

**Comment by pllim** [comment]
FWIW, if this is the stuff that calls stsynphot , the obsmode stuff is only currently set up for HST anyway... No other telescopes want to write their own https://stsynphot.readthedocs.io/en/latest/stsynphot/appendixc.html 🤷

**Comment by duytnguyendtn** [comment]
> stuff that calls stsynphot

Not exactly? These reffiles are needed to calculate our Geometric Transformations, which are used in the simulations that use STSynphot. But other than that, these reffiles don't call on the stsynphot code, so probably no need for concern. Though that does open my eyes that this puts a limitation that we can only properly simulate HST and effectively roadblocks us to simulating other telescopes (namely jwst) natively with our current stack...

**Pull request merged**
