### PR TITLE
Introduce G141 comparison tests against parallel packages

### PR DESCRIPTION
**Pull request by duytnguyendtn**
In https://github.com/spacetelescope/astrogrism_sandbox/pull/10, @ivastar introduced some tests to help ensure our development is producing accurate results. This PR migrates those tests, which currently rest in a notebook, into official unit tests for astrogrism. This is blocked by repo initialization PR #2

### CODE REVIEW

**Comment by rosteen** [comment]
First thought: I'd rather have a couple `.npy` files with the Grizli data saved in a `test_data` folder than have those large arrays defined in code.

**Review by rosteen — CHANGES_REQUESTED** [review]
More review thoughts: I don't think there's any need to compare against both GRISMCONF and Grizli - they should both be outputting the same values. In fact, since we have the correct values to test against, we probably don't need to refer to (or import) the other packages at all. Maybe just add a comment documenting that that's where the values were originally sourced from/checked against.

I also think there would be a lot of value in having tests for successful round-tripping of values within acceptable thresholds, e.g. testing `world` -> `grism_detector` and back for the reference pixel coordinates.

**Comment by rosteen** [comment]
I guess the upside of importing `GRISMCONF` to test against is that we wouldn't need to manually update the target values when the configuration files get updated.

**Comment by duytnguyendtn** [comment]
I didn't know about Numpy Array Files! Super cool suggestion. Implemented and pushed. 

As for the rest:
* Personally, for reproducibility, I'd argue it would be best to calculate the files on the fly as opposed to relying on precalculated values (even if we note where they came from). I think you also highlight the advantage of this approach above, being that astrogrism will respond to changes to any of our underlying packages. AFAIK, the goal of this effort was to test astrogrism *against* the other packages, not necessarily against a precalculated, absolute truth, hence this approach
* Also agree testing round-tripping would be useful, but outside the initial estimate of this task (that being, a direct translation of @ivastar's tests introduced in https://github.com/spacetelescope/astrogrism_sandbox/pull/10). I'd suggest merging this and adding any additional tests we'd want to run as follow up work

**Comment by rosteen** [comment]
I kind of think we should just ditch the Grizli test, since the values are hard-coded (so it doesn't give us a dynamic test) and the values are the same as come out of GRISMCONF. It seems like just having the GRISMCONF test hits the "test dynamically against another package" well enough. But I'll merge this as is for now and we can remove the Grizli test in the followup to add round trip tests.

**Pull request merged**
